name: hc_immobilier
description: Application de gestion immobilière HouseConnect
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # HTTP & API
  dio: ^5.4.0
  http: ^1.1.2
  connectivity_plus: ^7.0.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # UI Components
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.0.0
  flutter_svg: ^2.0.9

  # Navigation & Routing
  go_router: ^13.0.0

  # WebView pour paiements
  webview_flutter: ^4.5.0

  # Notifications Push
  onesignal_flutter: ^5.0.4

  # Date & Time
  intl: ^0.19.0

  # Images & Media
  image_picker: ^1.0.7
  photo_view: ^0.14.0

  # Utils
  url_launcher: ^6.2.3
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

  # JSON Serialization
  json_annotation: ^4.8.1


  pinput: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1

  # Hive Generator
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    # Images
    - assets/images/
    - assets/images/onboarding/
    - assets/images/placeholders/
    
    # Icons
    - assets/icons/
    
    # Animations Lottie
    - assets/animations/
    
    # Logos
    - assets/logo/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# Configuration de l'icône de l'application
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"
  adaptive_icon_background: "#1E3A8A"
  adaptive_icon_foreground: "assets/logo/app_icon_foreground.png"

# Configuration du splash screen
flutter_native_splash:
  color: "#1E3A8A"
  image: assets/logo/splash_logo.png
  android: true
  ios: true
  android_12:
    color: "#1E3A8A"
    image: assets/logo/splash_logo.png